# Generated by Django 4.2.30 on 2026-05-07 12:16

from django.db import migrations, models
import django.db.models.deletion
import sync_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.UUIDField(default=sync_app.models.generate_uuid, editable=False, primary_key=True, serialize=False)),
                ('path', models.CharField(max_length=500, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('is_deleted', models.BooleanField(default=False)),
                ('current_version', models.IntegerField(default=1)),
                ('last_modified_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FileVersion',
            fields=[
                ('id', models.UUIDField(default=sync_app.models.generate_uuid, editable=False, primary_key=True, serialize=False)),
                ('version_num', models.IntegerField()),
                ('operation_type', models.CharField(choices=[('CREATE', 'Create'), ('MODIFY', 'Modify'), ('DELETE', 'Delete'), ('RENAME', 'Rename'), ('RESTORE', 'Restore')], max_length=20)),
                ('hash', models.CharField(blank=True, max_length=128, null=True)),
                ('size', models.BigIntegerField(default=0)),
                ('storage_path', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='sync_app.file')),
            ],
        ),
    ]
