# Generated by Django 4.2.30 on 2026-06-01 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sync_app", "0002_folder"),
    ]

    operations = [
        migrations.AddField(
            model_name="file",
            name="thumbnail_path",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
